// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/kainonly/worker/app"
	"github.com/kainonly/worker/common"
)

// Injectors from wire.go:

func NewApp() (*app.App, error) {
	values, err := LoadStaticValues()
	if err != nil {
		return nil, err
	}
	logger, err := UseZap()
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(values)
	if err != nil {
		return nil, err
	}
	jetStream, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		V:    values,
		Log:  logger,
		Nats: conn,
		Js:   jetStream,
	}
	appApp := app.Initialize(inject)
	return appApp, nil
}
