app:
  name: lab-scf
  key:
database:
  dsn: 'user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local'
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
cookie:
  secure: true
  http_only: true
  same_site: strict
cors: [ '*' ]
auth:
  app:
    aud: [ 'app' ]
    exp: 3600
