app:
  name: lab-scf
  key:
database:
  dsn: 'host= user= password= dbname=example TimeZone=Asia/Shanghai'
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
cookie:
  secure: true
  http_only: true
  same_site: strict
cors: [ '*' ]
auth:
  app:
    aud: [ 'app' ]
    exp: 3600
